# Using YAML file enable us to create the 2 Fargate profiles:

# Check eksctl.io documentation for up to date template:
apiVersion: eksctl.io/v1alpha5

kind: ClusterConfig

# Metadata is required here ! Provide cluster name and region !
metadata:
  name: eksdemo1  # Name of the EKS Cluster
  region: us-east-1

fargateProfiles:
  - name: fp-app2
    selectors:
      # All workloads in the "ns-app2" Kubernetes namespace will be
      # scheduled onto Fargate:      
      - namespace: ns-app2
  - name: fp-ums
    selectors:
      # All workloads in the "ns-ums" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:      
      - namespace: ns-ums
        labels:
          # Here the workload label also match !
          runon: fargate     
